DROP TYPE IF EXISTS gaming_platform;
DROP TYPE IF EXISTS user_rank;
DROP TYPE IF EXISTS rank_division;
DROP TYPE IF EXISTS item_category;
DROP TYPE IF EXISTS item_color;
DROP TYPE IF EXISTS item_certification;
DROP TYPE IF EXISTS item_rarity;
DROP TYPE IF EXISTS item_special_edition;

CREATE TYPE gaming_platform AS ENUM(
    'PC',
    'PS4',
    'Nintendo Switch',
    'Xbox one'
);

CREATE TYPE user_rank AS ENUM(
    'Grand Champion',
    'Champion III',
    'Champion II',
    'Champion I',
    'Diamond III',
    'Diamond II',
    'Diamond I',
    'Platinum III',
    'Platinum II',
    'Platinum I',
    'Gold III',
    'Gold II',
    'Gold I',
    'Silver III',
    'Silver II',
    'Silver I',
    'Bronze III',
    'Bronze II',
    'Bronze I',
    'Unranked'
);

CREATE TYPE rank_division AS ENUM(
    'IV',
    'III',
    'II',
    'I'
);

CREATE TYPE item_category AS ENUM(
    'Body', 
    'Decal', 
    'Paint Finish', 
    'Wheels', 
    'Rocket Boost', 
    'Toppers', 
    'Antenna', 
    'Goal Explosion', 
    'Trails', 
    'Player Banner', 
    'Engine Audio'
);

CREATE TYPE item_color AS ENUM(
    'Black', 
    'Burnt Sienna', 
    'Cobalt', 
    'Crimson', 
    'Forest Green', 
    'Grey', 
    'Lime', 
    'Orange', 
    'Pink', 
    'Purple', 
    'Saffron', 
    'Sky Blue', 
    'Titanium White'
);

CREATE TYPE item_certification AS ENUM(
    'Acrobat', 
    'Aviator', 
    'Goalkeeper', 
    'Guardian', 
    'Juggler', 
    'Paragon', 
    'Playmaker', 
    'Scorer', 
    'Show-Off', 
    'Sniper', 
    'Striker', 
    'Sweeper', 
    'Tactician', 
    'Turtle', 
    'Victor'
);

CREATE TYPE item_name AS ENUM(
    "20XX",
    "2Bold",
    "2Cool",
    "2Tuff",
    "4Player Network",
    "'70 Dodge Charger R/T",
    "'80s Grad",
    "'89 Batmobile",
    "8-Ball",
    "'99 Nissan Skyline GT-R R34",
    "9GAG",
    "AbleGamers",
    "Accelerato",
    "Achievement Hunter",
    "Aero Mage",
    "Aether",
    "Afghanistan",
    "Afterlife",
    "Aftershock v2",
    "Aftershock",
    "Aiobahn",
    "Alameda Twin",
    "Albania",
    "Alchemist",
    "Algeria",
    "Alien",
    "Almas",
    "American Samoa",
    "Andorra",
    "Angel Wings",
    "Angola",
    "Angry Army",
    "Anguilla",
    "Animus GP",
    "Animus GP: Peacock",
    "Anna Yvette",
    "Anne Munition",
    "Anodized",
    "Anticlipse",
    "Antigua&Barbuda",
    "Antlers",
    "Anubis",
    "Apex",
    "Aquaman",
    "Aqueous",
    "ARA-51",
    "Arachnotenna",
    "ARC",
    "Arcadia",
    "Arcana",
    "Argentina",
    "Armada",
    "Armadillo",
    "Armenia",
    "Arrowhead",
    "Arsenal",
    "Aruba",
    "Asterias",
    "Athena",
    "Atlanta Hawks",
    "Atomizer",
    "Australia",
    "Austria",
    "AWD",
    "Azerbaijan",
    "Backfire",
    "Bad Computer",
    "Bahamas",
    "Bahrain",
    "Ball King",
    "Balla-Carrà",
    "Baller",
    "Ballistic",
    "Balloon Dog",
    "Bangladesh",
    "Barbados",
    "Baseball Cap", ("B)",
    "Baseball Cap", ("F)",
    "Batman",
    "Batmobile",
    "Battle-Cars Anniversary",
    "Battle-Stars",
    "Battleworn",
    "Beach Party",
    "Beaten Egg",
    "Belarus",
    "Belgium",
    "Belize",
    "Bender",
    "Benin",
    "Beret",
    "Bermuda",
    "Bhutan",
    "Big Buck",
    "Big Scratches",
    "Biker Cap",
    "Binary",
    "Biomass",
    "Birthday Bash",
    "Birthday Cake",
    "Black Market Preview",
    "Blacklight",
    "Blacklight: Retribution",
    "Blackwork",
    "Blamite Overthruster",
    "Blast Off",
    "Blast Ray",
    "Blazer",
    "Blitzen",
    "Block Trim",
    "Block",
    "Blue Chequered Flag",
    "Blueprint",
    "Bobby Helmet",
    "Bolivia",
    "Bomani",
    "Bomb Pole",
    "Bomber",
    "Bone Jack",
    "Bone King",
    "Bone Shaker",
    "BOO!",
    "Boombox",
    "Boo-ya!",
    "Bosnia and Herzegovina",
    "Bossfight",
    "Boston Celtics",
    "Botswana",
    "Bowler",
    "Brazil",
    "Breakout Type-S v2",
    "Breakout Type-S",
    "Breakout",
    "Breakout: 9 Lives",
    "Breakout: Astaroth",
    "Breakout: Bobcat",
    "Breakout: CRL Western",
    "Breakout: Nice Shot",
    "Breakout: Ripped Comic",
    "Breakout: Sneaky Slither",
    "Breakout: What A Save!",
    "British Virgin Islands",
    "Brodie Helmet",
    "Brooklyn Nets",
    "Brunei",
    "Brünnehilde",
    "Brushed Metal",
    "Bubble Wand",
    "Bubbles",
    "Bubbly",
    "Bulgaria",
    "Bunny Ears",
    "Burkina Faso",
    "Burlap",
    "Burma",
    "Burnout",
    "Burundi",
    "Butterflies",
    "Butterfly",
    "Buzz Kill",
    "Buzzer",
    "Bycocket",
    "Caboodle",
    "Calavera",
    "Calculated",
    "Call Sign RL",
    "Callous Bros.",
    "Callous",
    "Cambodia",
    "Cameroon",
    "Camo Flag",
    "Camo",
    "Campaign Hat",
    "Canada",
    "Candle",
    "Candy Cane",
    "Candy Cane",
    "Candy Corn",
    "Canvas",
    "Capacitor I",
    "Capacitor II",
    "Capacitor III",
    "Capacitor IV",
    "Cape Verde Islands",
    "Captain's Hat",
    "Carbon Fiber",
    "Carbonated",
    "Carriage",
    "Catfish",
    "Cattleman",
    "Cauldron",
    "Cavalier",
    "Cayman Islands",
    "CDXL",
    "Centio V17",
    "Central Africa Republic",
    "Centro",
    "Chad",
    "Chafed Cherry",
    "Chainsaw",
    "Chakram",
    "Chameleon",
    "Charlotte Hornets",
    "Chaser",
    "Chef's Hat",
    "Cherry Top",
    "Chicago Bulls",
    "Chick Magnet",
    "Chile",
    "China",
    "Chinese Taipei",
    "Chivalry - Agatha Knights",
    "Chivalry - Mason Order",
    "Christmas Tree",
    "Christmas Wreath",
    "Chrono",
    "Chusho",
    "Circuit Board",
    "Circuit Pro",
    "Cirrus",
    "Clamshell",
    "Classic",
    "Clean Cut",
    "Cleveland Cavaliers",
    "Clockwork",
    "Cloudburst I",
    "Cloudburst II",
    "Cloudburst III",
    "Cobra",
    "Cockroach",
    "COG",
    "Cold Front",
    "Cold Fusion",
    "Cold Sweater",
    "Colombia",
    "Combat",
    "Combo",
    "Comet",
    "Community Flags",
    "Community",
    "Comoros",
    "Confetti",
    "Congo DR",
    "Congo",
    "Cook Islands",
    "Cookie Dough",
    "Copycat",
    "Coral",
    "Corroded Metal",
    "Costa Rica",
    "Côte d'Ivoire",
    "Country Flags",
    "Cow Skull",
    "Crash Dive",
    "Crazy Sandwich",
    "Crazy-8",
    "Crisscross",
    "Cristiano",
    "Critters",
    "CRL Eastern",
    "CRL Northern",
    "CRL Southern",
    "CRL Western",
    "Croatia",
    "Cromulon",
    "Cruxe",
    "Cryo-Flames",
    "Crystal",
    "Cuba",
    "Cuckoo Clock",
    "Cupcake",
    "Curacao",
    "Cutlass",
    "Cuttle Time",
    "Cyborg",
    "Cyclone",
    "Cyclone: Bat Boy",
    "Cyclone: Flames",
    "Cyclone: L-ITA 99",
    "Cyclone: Sliver",
    "Cyclone: Stripes",
    "Cyclone: Whiteout",
    "Cyclops",
    "Cyprus",
    "Cyrus",
    "Czech Republic",
    "Daddy-O",
    "Dallas Mavericks",
    "Dandelion Seed",
    "Dark Matter",
    "Darren Styles",
    "Datastream",
    "Dave's Bread",
    "Day TV",
    "Day of the Tentacle",
    "DC Comics",
    "Dead Serious",
    "deadmau5",
    "Debugged",
    "Decennium Pro",
    "Deerstalker",
    "DeLorean Time Machine",
    "Dendritic",
    "Denmark",
    "Denver Nuggets",
    "Derby Girl",
    "Derby",
    "Destructoid",
    "Detroit Pistons",
    "Devil Horns",
    "Diablo",
    "Dieci",
    "Diomedes",
    "Dion Timmer",
    "Disco Ball",
    "Disconnect",
    "Discord",
    "Discotheque",
    "Dissolver",
    "Distortion",
    "Div",
    "Dizzy Birds",
    "DJ Sushi",
    "Djibouti",
    "Dollar Sign",
    "Dominica",
    "Dominican Republic",
    "Dominus GT v2",
    "Dominus GT",
    "Dominus",
    "Dominus: CRL Eastern",
    "Dominus: CRL Southern",
    "Dominus: Dot Matrix",
    "Dominus: Proptosis",
    "Dominus: RC Rivals",
    "Dominus: Savage",
    "Dominus: Templar",
    "Donut",
    "Dot Matrix",
    "Dot Rush",
    "Dots",
    "Dougal",
    "Doughnut Eater",
    "Doughnut",
    "Draco",
    "Dragon Lord",
    "Dragon Wings",
    "Drink Helmet",
    "Drip Drop",
    "Dueling Dragons",
    "Dune Racer",
    "Duumu",
    "Dying Light",
    "Dying Light-Gas Tank",
    "Dynamo",
    "Dyno",
    "East Timor",
    "Easter Egg",
    "Easter Basket",
    "Echo-Pulse",
    "Ecuador",
    "Edge Of Space",
    "Egged",
    "Egypt",
    "EKG-OMG",
    "El Salvador",
    "Electroshock",
    "EMD1",
    "Enchanter",
    "Endo",
    "England",
    "EQ",
    "Equalizer",
    "Equatorial Guinea",
    "Eritrea",
    "ESL Champ",
    "ESL",
    "Esper",
    "Estonia",
    "Ethiopia",
    "Euphoria",
    "Euro Truck Simulator Rig",
    "Eyeball",
    "Falchion",
    "Falco",
    "Falkland Islands",
    "Fallen Tree",
    "Fallout-Vault Boy",
    "Fantasmo",
    "Faroe Islands",
    "Fast 4WD",
    "Fast 4WD: 50th Anniversary",
    "Fast 4WD: Diecast",
    "Fast 4WD: Hot Wheels Race Team",
    "Fast 4WD: Sleek",
    "Fathom",
    "Feather",
    "Feathered",
    "Fenix Rage",
    "Feral",
    "Fez",
    "FGSP",
    "Fiji",
    "Finland",
    "Fire God",
    "Fire Helmet",
    "Fireplug",
    "Fireworks",
    "Fishbowl",
    "Flagman",
    "Flames",
    "Flamethrower Blue",
    "Flamethrower Green",
    "Flamethrower Pink",
    "Flamethrower Purple",
    "Flamethrower Red",
    "Flamethrower Yellow",
    "Flamethrower",
    "Flex",
    "Flower Power",
    "Flower-Daisy",
    "Flower-Orchid",
    "Flower-Rose",
    "Flowers",
    "Flower-Sunflower",
    "Flower-Tulip",
    "Foam Finger",
    "Foam Hat",
    "Foreman",
    "Fractal Fire",
    "France",
    "Friction",
    "Froggy",
    "Frostbite",
    "Fruit Hat",
    "FSL",
    "Fugu",
    "Funhaus",
    "Funny Book",
    "Funnybook",
    "Furry",
    "Fuzzy Brute",
    "Fuzzy Skull",
    "Fuzzy Vamp",
    "GA-819 HB",
    "Gabon",
    "Gaiden",
    "Gaki",
    "Gale-Fire",
    "Gambia",
    "Game On",
    "Gamespot",
    "Gammer",
    "Gargoyle",
    "Gassy Mexican",
    "Gazella GT",
    "Gazella GT: 50th Anniversary",
    "Gazella GT: Diecast",
    "Gazella GT: Hot Wheels Race Team",
    "Gazella GT: Sleek",
    "Gearlock",
    "Genie Lamp",
    "Geo Soul",
    "Georgia",
    "Germany",
    "Gfinity",
    "GG the Clown",
    "Ghana",
    "Ghost",
    "Giant Panda",
    "Gibraltar",
    "Gigapede",
    "Gingerbread Man",
    "Gizmo",
    "Glossy Block",
    "Glossy",
    "Glyphtrix",
    "Goat Simulator-G2",
    "Goat Simulator-Goatenna",
    "Gobo",
    "Go-Kart",
    "Gold Glove",
    "Gold Nugget",
    "Gold Cap",
    "Gold Rush",
    "Golden State Warriors",
    "Goldfish",
    "Goldstone",
    "Good Graces",
    "Graduation Cap",
    "Grass",
    "Grave Robber",
    "Great White",
    "Greece",
    "Green Arrow",
    "Green Lantern",
    "Grenada",
    "Griffon",
    "Grimalkin",
    "Grog",
    "Guam",
    "Guatemala",
    "Guinea Bissau",
    "Guinea",
    "Guyana",
    "Haiti",
    "Hallowtide",
    "Halo",
    "Hammerhead",
    "Happy Holidays",
    "Happy Penguin",
    "Hard Hat",
    "Harpoon",
    "Hawaiian Lei",
    "Headlander-Starcophagus",
    "Heart Glasses",
    "Heart",
    "Hearts",
    "Heatwave",
    "Heiwa",
    "Helios",
    "Hellfire",
    "Helper Elf",
    "Hexed",
    "Hexphase",
    "Hikari P5",
    "Hip-Hop",
    "Hiro",
    "Hi-Tech",
    "Hoagie",
    "Hogsticker",
    "Holiday Gift",
    "Holiday Stocking",
    "Holiday Bow",
    "Holiday Deco",
    "Holiday Gifts",
    "Homburg",
    "Home Stretch",
    "Honduras",
    "Hong Kong",
    "Horseshoe",
    "Horus",
    "Hot Dog",
    "Hot Wheels 50th",
    "Hot Wheels",
    "Hot Hot Wheels", 
    "Hot Rocks",
    "Hot Rod",
    "Hot Wheels 50th",
    "Hot Wheels Gorilla",
    "Hot Wheels RC Rivals",
    "Hot Wheels Snake",
    "Hot Wheels Spider",
    "Hot Wheels",
    "Hotcakes",
    "Hotshot",
    "Houston Rockets",
    "Howler",
    "Hula Girl",
    "Humble Pie",
    "Hungary",
    "Hustle Brows",
    "Hydro",
    "Hyper",
    "Hyper-Flight",
    "Hypernova",
    "Hypnotik",
    "Ice Charger",
    "Ice Pop",
    "Iceland",
    "IGN",
    "Illuminata",
    "Imperator DT5",
    "Imulsion",
    "India",
    "Indiana Pacers",
    "Indonesia",
    "Infected Mushroom",
    "Inferno",
    "Infinium",
    "InGen",
    "Ink",
    "Inked",
    "Instinct",
    "Interceptor",
    "Intercom",
    "Interdimensional GB",
    "Invader",
    "Inverness",
    "Ion Green",
    "Ion Pink",
    "Ion Purple",
    "Ion Red",
    "Ion Yellow",
    "Ion",
    "Iran",
    "Iraq",
    "Ireland",
    "Iris",
    "Ishihara",
    "Island Scales",
    "Isle Of Man",
    "Israel",
    "Italy",
    "itmeJP",
    "Ivy Cap",
    "J!NX",
    "Jack-in-the-Box",
    "Jäger 619 RS",
    "Jäger 619 RS: Shark Tooth",
    "Jäger 619 RS: StarLighter",
    "Jamaica",
    "Japan",
    "Javelin",
    "Jetstream",
    "Jiangshi",
    "Jolly Roger",
    "Jolt Bangle I",
    "Jolt Bangle II",
    "Jolt Bangle III",
    "Jon Sandman",
    "Jordan",
    "Juiced",
    "Junk Food",
    "Jurassic Park",
    "Jurassic World",
    "Jurassic Jeep® Wrangler",
    "Jurassic Park Hard Hat",
    "Jurassic Park",
    "Jurassic World",
    "K2",
    "Kaiju",
    "Kaleidoscope",
    "Kalos",
    "Kawaii",
    "Kayak",
    "Kazakhstan",
    "Kaze",
    "Kenya",
    "Kilowatt",
    "Kiribati",
    "Knitted Yarn",
    "Koinobori",
    "Kosovo",
    "Koven",
    "Kraken",
    "Kuwait",
    "Kyrgyzstan",
    "Kyrios",
    "Labyrinth",
    "Ladybug",
    "Laos",
    "Laser Wave I",
    "Laser Wave II",
    "Laser Wave III",
    "Latte",
    "Latvia",
    "Lebanon",
    "Leopard",
    "Lepus",
    "Lesotho",
    "Leviathan",
    "LFT",
    "Liberia",
    "Libertine",
    "Libya",
    "Lift-Off",
    "Light Bulb",
    "Lightning Bolt",
    "Lightning Yellow",
    "Lightning",
    "Lightspeed",
    "Linguist",
    "LIRIK",
    "L-ITA 99",
    "Lithuania",
    "Little Bow",
    "Little Bunny",
    "Little Cow",
    "Little Dog",
    "Little Elephant",
    "Little Owl",
    "Little Sloth",
    "Lobo",
    "Locomotive",
    "Lollipop",
    "lolRenaynay",
    "Lone Wolf",
    "Looper",
    "Loot Crate",
    "Los Angeles Clippers",
    "Los Angeles Lakers",
    "Lowrider",
    "Lucci",
    "Luminous",
    "Lustrum X10",
    "Luxembourg",
    "Macaron",
    "Macau",
    "Macedonia",
    "Machina",
    "Madagascar",
    "Mage Glass I",
    "Mage Glass II",
    "Mage Glass III",
    "Magic Missile",
    "Magmus",
    "Mainframe",
    "Makai",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Mantis",
    "Marauder v2",
    "Marauder",
    "Mariachi Hat",
    "Mario NSR",
    "Marshall Islands",
    "Masamune",
    "Masato",
    "Matte",
    "Mauritania",
    "Mauritius",
    "Maverick G1",
    "Maverick GXT",
    "Maverick",
    "Maximon",
    "Maxx",
    "MDGA",
    "Mean Streak",
    "Medic",
    "Memphis Grizzlies",
    "Merc",
    "Merc: B.B. Wolf",
    "Meridian",
    "Metallic (Rough)",
    "Metallic (Smooth)",
    "Metallic Flake",
    "Metallic Pearl (Smooth)",
    "Metallic Pearl",
    "Metallic",
    "Mexico",
    "MG-88",
    "Miami Heat",
    "Micronesia",
    "Midnight D",
    "Migraine",
    "Milwaukee Bucks",
    "Minnesota Timberwolves",
    "Min-Spec",
    "MiNT",
    "MIRV",
    "Mister Monsoon",
    "MLG",
    "MMS Headphones",
    "Moai",
    "Mobo",
    "Moderator",
    "Modus Bestia",
    "Mohawk",
    "Moldova",
    "Monaco",
    "Mondo",
    "Money",
    "Mongolia",
    "Monstercat Uncaged",
    "Monstercat",
    "Montenegro",
    "Montserrat",
    "Monza",
    "Moon Rock",
    "Morocco",
    "Morty",
    "Mosher",
    "Mothership Pro",
    "Motor Monster",
    "Motormouth",
    "Mount Champion",
    "Mountaineer",
    "Mouse Cat",
    "Mouse Trap",
    "Mozambique",
    "Mr Toasty",
    "Mr. Banana",
    "Mr. Hot Dog",
    "Mr. Hot Pepper",
    "Mr. Meeseeks",
    "Mr. PBH",
    "Mr. Pineapple",
    "MR11",
    "MR11: 50th Anniversary",
    "MR11: Diecast",
    "MR11: Hot Wheels Race Team",
    "MR11: Sleek",
    "Mrs. Avocado",
    "Muerto",
    "Mummified",
    "Muscle Car",
    "Muzzy",
    "Mystery Item",
    "Mystery Universal Decal",
    "Namesake",
    "Namibia",
    "Narwhal",
    "Nauru",
    "NBA Flags",
    "NBA",
    "NBP",
    "Necro",
    "Neo",
    "NeoGAF",
    "Neo-Thermal",
    "Nepal",
    "Neptune",
    "Netherlands",
    "Netherworld",
    "New Caledonia",
    "New Orleans Pelicans",
    "New York Knicks",
    "New Zealand",
    "New Year's 2017",
    "Nicaragua",
    "Nice Slice",
    "Nigeria",
    "Nine Lives",
    "Ninja",
    "Nipper",
    "Nitrous",
    "NNTR",
    "NoClip",
    "North Korea",
    "North Mariana Islands",
    "Northern Ireland",
    "Norway",
    "NSR",
    "Nutcracker",
    "Nuts & Bolts",
    "NVIDIA SHIELD",
    "NVIDIA",
    "NZXT",
    "Ockie",
    "Octane ZSR v2",
    "Octane ZSR",
    "Octane ZSR: Mechaceph",
    "Octane",
    "Octane: Chantico",
    "Octane: CRL Northern",
    "Octane: Dr. Thrash",
    "Octane: Island King",
    "Octane: Nice Shot",
    "Octane: Noooo!",
    "Octane: RC Rivals",
    "Octane: Space Cadet",
    "Octane: Turtle Tribe",
    "Octavian",
    "Octopus",
    "Odd Fish",
    "Oddworld-Abe",
    "Oddworld-Molluck",
    "Oddworld-Necrum",
    "Oddworld-RuptureFarms",
    "OEM",
    "OEM-A v2",
    "OEM-A",
    "OEM-B v2",
    "OEM-B",
    "OEM-C v2",
    "OEM-C",
    "OEM-D v2",
    "OEM-D",
    "OH5",
    "Oklahoma City Thunder",
    "Old Flame",
    "Oman",
    "Oni",
    "Operation Sports",
    "Orlando Magic",
    "Otaku",
    "OutaTime",
    "Overcharge",
    "Overhaul",
    "Overline",
    "Pakistan",
    "Paladin",
    "Palau",
    "Palestine",
    "Palm Tree",
    "Panama",
    "Panic Button",
    "Paper Boat",
    "Papua New Guinea",
    "Paraguay",
    "Parallax",
    "Parrot",
    "Partly Cloudy",
    "Party Hat",
    "Party Time",
    "Party-Chan",
    "PAX",
    "PC Gamer",
    "Peace Sign",
    "Peace",
    "Pearlescent (Matte)",
    "Pearlescent",
    "Pegasus",
    "Pegboard Nerds",
    "Penny Arcade",
    "Peppermint",
    "Peru",
    "Philadelphia 76ers",
    "Philippines",
    "Phoenix Suns",
    "Phoenix Wings I",
    "Phoenix Wings II",
    "Phoenix Wings III",
    "Photon",
    "Pigeon",
    "Piñata",
    "Pinwheel",
    "Pirate's Hat",
    "Pixel Terror",
    "Pixel Fire",
    "Pixelated Shades",
    "Pizza Topper",
    "Plasma",
    "Playtime",
    "Plunger",
    "Poland",
    "Polar Force",
    "Polaris",
    "Police Hat",
    "Pollinator",
    "Pollo Caliente",
    "Poly Pop",
    "Polygonal",
    "Popcorn",
    "Pork Pie",
    "Portal - Cake",
    "Portal - Conversion Gel",
    "Portal - Propulsion Gel",
    "Portal - Repulsion Gel",
    "Portal-Aperture Laboratories",
    "Portal-Cake Sticker",
    "Portal-Companion Cube",
    "Portal-PotatOS",
    "Portal-Wheatley",
    "Portland Trail Blazers",
    "Portugal",
    "Power-Shot",
    "Primo",
    "Pro",
    "Propellerhead",
    "Pro-Street",
    "Proteus v2",
    "Proteus",
    "Proton",
    "Protostar",
    "Protractor",
    "Psyonix",
    "Puerto Rico",
    "Pulsus",
    "Puma",
    "Pumpkin",
    "Puntland",
    "Pyramidia",
    "Pyro",
    "Python",
    "Qatar",
    "Quimby",
    "Racer",
    "Rad Reindeer",
    "Radioactive",
    "Radium",
    "Ragnarok",
    "Rainbow Flag",
    "Rainbow",
    "Rakugaki",
    "Rally",
    "Rasta",
    "Rat Rod",
    "Razer",
    "Razzle",
    "Reactor",
    "Reaper",
    "Reddit Snoo",
    "Reddit",
    "REEVRB",
    "Reiko",
    "Republic of Niger",
    "Retro Ball - Urban",
    "Retro Ball - Utopia",
    "Retro Ball - Wasteland",
    "Réunion",
    "Revenant",
    "Rhino Horns",
    "Rhino",
    "Rick",
    "Righteous Sun",
    "Ripped Comic",
    "Ripper",
    "RL Garage",
    "RL Esports",
    "RLCS",
    "Road Hog XL v2",
    "Road Hog XL",
    "Road Hog",
    "Road Rage",
    "Roadkill",
    "Roasted",
    "ROBO-Visor",
    "Rockat",
    "Rocket Beans TV",
    "Rocket Labs",
    "Rocket",
    "Romania",
    "Rooster Teeth",
    "Rooster Comb",
    "Rose King",
    "Roulette",
    "Royal Crown",
    "Royal Tyrant",
    "Royalty",
    "Rubber Duckie",
    "Ruffian",
    "Russia",
    "Rwanda",
    "S Watercolour",
    "S. Watercolour",
    "Sacramento Kings",
    "Sacred",
    "Sad Sapling",
    "Sad Strawberry",
    "Safari",
    "Safety Flag",
    "Saint Kitts&Nevis",
    "Saint Lucia",
    "Saint Vincent",
    "Salty",
    "Samoa",
    "Samurai",
    "Samus's Gunship",
    "San Antonio Spurs",
    "San Marino",
    "Sanchez DC-137",
    "Sand Castle",
    "Sandstorm",
    "Santa Fe",
    "Santa",
    "Sao Tome",
    "Saptarishi",
    "Sara Skinner",
    "SARPBC-10",
    "Satellite",
    "Saturn",
    "Saudi Arabia",
    "Saudi Gamer",
    "Scarab",
    "Scarecrow Jack",
    "Scary Pumpkin",
    "Scorpions",
    "Scotland",
    "ScrewAttack",
    "SDMN FC",
    "Season 1 - Bronze",
    "Season 1 - Gold",
    "Season 1 - Platinum",
    "Season 1 - Silver",
    "Season 2 - Challenger",
    "Season 2 - Champion",
    "Season 2 - Prospect",
    "Season 2 - Star",
    "Season 3 - Challenger",
    "Season 3 - Champion",
    "Season 3 - Prospect",
    "Season 3 - Star",
    "Season 4 - Bronze",
    "Season 4 - Champion",
    "Season 4 - Diamond",
    "Season 4 - Gold",
    "Season 4 - Platinum",
    "Season 4 - Silver",
    "Season 5 - Bronze", ("Dragon)",
    "Season 5 - Bronze",
    "Season 5 - Champion", ("Dragon)",
    "Season 5 - Champion",
    "Season 5 - Diamond", ("Dragon)",
    "Season 5 - Diamond",
    "Season 5 - Gold", ("Dragon)",
    "Season 5 - Gold",
    "Season 5 - Grand Champion", ("Dragon)",
    "Season 5 - Grand Champion",
    "Season 5 - Platinum", ("Dragon)",
    "Season 5 - Platinum",
    "Season 5 - Silver", ("Dragon)",
    "Season 5 - Silver",
    "Season 6 - Bronze",
    "Season 6 - Champion",
    "Season 6 - Diamond",
    "Season 6 - Gold",
    "Season 6 - Platinum",
    "Season 6 - Silver",
    "Season 7 - Tier 1",
    "Season 7 - Tier 2",
    "Season 7 - Tier 3",
    "Season 7 - Tier 4",
    "Season 7 - Tier 5",
    "Season 7 - Tier 6",
    "Season 7 - Tier 7",
    "Season 8 - Bronze",
    "Season 8 - Champion",
    "Season 8 - Diamond",
    "Season 8 - Gold",
    "Season 8 - Platinum",
    "Season 8 - Silver",
    "Seastar",
    "Seismic",
    "Semigloss",
    "Senegal",
    "Septem",
    "Serbia",
    "Serious Gaming",
    "Servergate",
    "Seychelles",
    "Shacknews",
    "Shadow Witch",
    "Shadowgate",
    "Shank",
    "ShapeRacer",
    "Shapeshifter",
    "Shark Attack",
    "Shark Bite",
    "Shark Fin",
    "Sharp Flames",
    "Shattered",
    "Shibuya",
    "Shisa",
    "Shockwave",
    "Shooting Star",
    "Shot Fox",
    "Shuriken",
    "Sierra Leone",
    "Siiick Reads",
    "Sinclair",
    "Singapore",
    "Singularity",
    "Skull",
    "Skullcap",
    "Skullface",
    "Skulls",
    "Skyelle",
    "Slime",
    "Slimed",
    "Slimline",
    "Slippy",
    "Slipstream",
    "SLK",
    "Slovakia",
    "Slovenia",
    "Smiley Face",
    "Smore'd",
    "S'mored",
    "Snakeskin",
    "Snowboards",
    "Snowflakes",
    "Snowman",
    "Soccar Nebula",
    "Soccer Ball",
    "Soccer Ball",
    "Soccer Splash",
    "Solar System",
    "Solomon Islands",
    "Somalia",
    "Somaliland",
    "Sombrero",
    "Something Awful",
    "Soupandreas",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Sovereign A/T",
    "Sovereign Pro",
    "Space Trip",
    "Space Worm",
    "Spain",
    "Sparkles",
    "Spartan Sam",
    "Spatter",
    "Spectre",
    "Speed Force",
    "Speedster",
    "Spikes",
    "Spinner",
    "Spiralis",
    "Splashback",
    "Splatter",
    "Spooky1611",
    "Springtime Flowers",
    "Spyder",
    "Sri Lanka",
    "Stainless Steel",
    "Stallion",
    "Standard Blue",
    "Standard Green",
    "Standard Orange",
    "Standard Pink",
    "Standard Purple",
    "Standard Yellow",
    "Standard",
    "Star Swash",
    "Star",
    "Starbase ARC",
    "Staredown",
    "Stars",
    "Starstruck",
    "Stegosaur",
    "Stephen Walking",
    "Stern",
    "Sticker Bomb",
    "Stitches",
    "Stoic Muffin",
    "Stonebank",
    "Storm Warning",
    "Storm Watch",
    "Streamline",
    "Strike Vector EX",
    "Striker Legend",
    "Striker Pro",
    "Striker",
    "Stripe Racer",
    "Stripes",
    "Sub-Zero",
    "Succulents",
    "Sudan",
    "Suji",
    "Sun Ray",
    "Sunburst",
    "Sundae",
    "Sun-Damaged",
    "Sundial",
    "Super F3",
    "Super RX-T",
    "Super Star",
    "Superman",
    "Supernova I",
    "Supernova II",
    "Supernova III",
    "Surfboard",
    "Suriname",
    "Sushi Nigiri",
    "Sushi Roll",
    "Swaziland",
    "Sweden",
    "Sweet Tooth",
    "Sweet Tooth",
    "Swim Ring",
    "Swirls",
    "Switzerland",
    "SWT-T",
    "Syria",
    "T. rex",
    "Tachyon",
    "Taco",
    "Tagged",
    "Tahiti",
    "Tajikistan",
    "Takumi RX-T v2",
    "Takumi RX-T",
    "Takumi",
    "Tanzania",
    "Tats",
    "Taxi Topper",
    "Taxi",
    "Team Fat",
    "Team PowA",
    "Tech",
    "Techno",
    "Tempest",
    "Tennis Ball",
    "Thailand",
    "Thanatos",
    "The Attack",
    "The Game Awards-Logo",
    "The Game Awards-Statue",
    "The Clutch",
    "The Dark Knight Rises Tumbler",
    "The Flash",
    "The Summit",
    "Thermal Blue",
    "Thermal Green",
    "Thermal Pink",
    "Thermal Purple",
    "Thermal Yellow",
    "Thermal",
    "Thread-X2",
    "Thunderspeck",
    "Tiara",
    "Tiger Shark",
    "Tiger Tiger",
    "Tiger",
    "Togo",
    "Tokyo Machine",
    "Tomahawk",
    "Tonga",
    "Toon Glossy",
    "Toon Hydro",
    "Toon Matte",
    "Toon Sketch",
    "Toon Smoke",
    "Toon Wood",
    "Toon",
    "Top Hat",
    "Topographic",
    "Tora",
    "Toronto Raptors",
    "Torrent",
    "Tourney Champ",
    "Trace Racer",
    "Traffic Cone",
    "Trahere",
    "Trash It!",
    "Treasure Hunt",
    "Treasure",
    "Triangle",
    "Tribal",
    "Trident",
    "Trigon",
    "Trinidad and Tobago",
    "Trinity",
    "Triplex",
    "Triplicate",
    "Triton v2",
    "Triton",
    "Troika",
    "Troublemaker I",
    "Troublemaker II",
    "Troublemaker III",
    "Troublemaker IV",
    "Trucker Hat",
    "Tsunami Beam",
    "Tunica",
    "Tunisia",
    "Turbine",
    "Turbo",
    "Turkey",
    "Turkmenistan",
    "Turks&Caicos",
    "Turtle",
    "Tuvalu",
    "Twin Mill III",
    "Twinzer",
    "Twisted Tree",
    "Twitch",
    "Two-Timer",
    "UFO",
    "Uganda",
    "Ukraine",
    "Uncaged Cat",
    "Uncaged",
    "Uncle Sam",
    "Undying Love",
    "Unicorn",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Unmasked",
    "Unreal Frag Center",
    "Unreal Tournament - Flak Shell",
    "Unreal Tournament - Red",
    "Unreal Tournament (Classic)",
    "Unreal Tournament 2004",
    "Unreal Tournament",
    "Unreal Tournament-Blue",
    "Unreal",
    "Uproar",
    "Uruguay",
    "US Virgin Islands",
    "Utah Jazz",
    "UV Turret",
    "Uzbekistan",
    "Vagabond",
    "Vampire Bat   ",
    "Vanuatu",
    "Vatican City",
    "Vector",
    "Veloce",
    "Venezuela",
    "Venom",
    "Venus Flytrap",
    "Vice",
    "Video Games",
    "Vietnam",
    "Vikkstar",
    "Virtual Wave",
    "Visor",
    "Voltaic",
    "Vortex",
    "Vulcan",
    "Waffle",
    "Wales",
    "Warframe",
    "Warframe-Chroma",
    "Warframe-Excalibur",
    "Warframe-Loki",
    "Warlock",
    "Warm Watermelon",
    "Washington Wizards",
    "Watermelon",
    "Wave Beam",
    "Werewolf",
    "Western Sahara",
    "Wheelman",
    "White Flag",
    "White Hat",
    "Whizzle",
    "Widow's Web",
    "Wildcat Ears",
    "Wildfire",
    "Windswept",
    "Wings",
    "Winning Streak",
    "Winter Storm",
    "Winter's Warmth",
    "Witcher Medallion",
    "Witch's Hat",
    "Wizard Hat",
    "Wonder Woman",
    "Wonder Woman",
    "Wonderment",
    "Wood",
    "Woofless",
    "Work Boot",
    "Worms W.M.D",
    "Worms W.M.D. Grenade",
    "Worms W.M.D.",
    "Worried Watermelon",
    "WW5SP",
    "WWE Monday Night RAW",
    "WWE NXT",
    "WWE SmackDown Live",
    "WWE WrestleMania 34",
    "WWE Monday Night RAW",
    "WWE NXT",
    "WWE SmackDown Live!",
    "WWE WrestleMania 34",
    "WWE",
    "X Games",
    "X-Devil Mk2 v2",
    "X-Devil Mk2",
    "X-Devil",
    "X-Devil: Devil's Advocate",
    "X-Devil: Dot Matrix",
    "Xenosplash",
    "Xmas",
    "XVI",
    "XVIII",
    "Yemen",
    "YouTube Gaming",
    "Yuletide",
    "Yuzo",
    "Zambia",
    "Zebra",
    "Zeta",
    "Zhangtek",
    "Zigzag",
    "Zimbabwe",
    "Zippy",
    "Zomba",
    "Zombie",
    "Z-Plate",
    "ZT-17"
);

CREATE TYPE item_rarity AS ENUM(
    'Common', 
    'Uncommon', 
    'Rare', 
    'Very Rare', 
    'Import', 
    'Exotic', 
    'Black Market', 
    'Premium', 
    'Limited'
);

CREATE TYPE item_special_edition AS ENUM(
    'Inverted', 
    'Infinite', 
    'Holographic'
);

CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    fname TEXT NOT NULL,
    lname TEXT NOT NULL,
    platform gaming_platform NOT NULL,
    gamertag TEXT NOT NULL,
    rocket_id TEXT NULL,
    rank user_rank NOT NULL,
    division rank_division NOT NULL,
    lft BOOLEAN NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password TEXT NOT NULL,
    bio VARCHAR(255),
    date_created TIMESTAMP DEFAULT now() NOT NULL
);

CREATE TABLE items (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    category item_category NOT NULL,
    item item_name NOT NULL,
    painted item_color NOT NULL,
    rarity item_rarity NOT NULL,
    certified item_certification NOT NULL,
    special_edition item_special_edition NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);

CREATE TABLE teams (
    userid INTEGER REFERENCES users(id) NOT NULL PRIMARY KEY,
    gamertag TEXT NOT NULL,
    platform gaming_platform NOT NULL,
    rank user_rank NOT NULL,
    division rank_division NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);

CREATE TABLE trades (
    id INTEGER UNIQUE GENERATED ALWAYS AS IDENTITY,
    userid REFERENCES users(id) NOT NULL,
    itemid REFERENCES items(id) NOT NULL,
    tradeid INTEGER GENERATED BY DEFAULT IDENTITY,
    PRIMARY KEY (userid, itemid)
);

CREATE TABLE inventory (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
    userid INTEGER REFERENCES users(id) NOT NULL,
    itemid INTEGER REFERENCES items(id) NOT NULL
)