DROP TABLE inventory;
DROP TABLE trades;
DROP TABLE items;
DROP TABLE teams;
DROP TABLE users;
DROP TYPE IF EXISTS gaming_platform;
DROP TYPE IF EXISTS user_rank;
DROP TYPE IF EXISTS rank_division;
DROP TYPE IF EXISTS item_category;
DROP TYPE IF EXISTS item_color;
DROP TYPE IF EXISTS item_certification;
DROP TYPE IF EXISTS item_name;
DROP TYPE IF EXISTS item_rarity;
DROP TYPE IF EXISTS item_special_edition;
