DROP TYPE IF EXISTS gaming_platform;
DROP TYPE IF EXISTS user_rank;
DROP TYPE IF EXISTS rank_division;
DROP TYPE IF EXISTS item_category;
DROP TYPE IF EXISTS item_color;
DROP TYPE IF EXISTS item_certification;
DROP TYPE IF EXISTS item_name;
DROP TYPE IF EXISTS item_rarity;
DROP TYPE IF EXISTS item_special_edition;

CREATE TYPE gaming_platform AS ENUM(
    'PC',
    'PS4',
    'Nintendo Switch',
    'Xbox one'
);

CREATE TYPE user_rank AS ENUM(
    'Grand Champion',
    'Champion III',
    'Champion II',
    'Champion I',
    'Diamond III',
    'Diamond II',
    'Diamond I',
    'Platinum III',
    'Platinum II',
    'Platinum I',
    'Gold III',
    'Gold II',
    'Gold I',
    'Silver III',
    'Silver II',
    'Silver I',
    'Bronze III',
    'Bronze II',
    'Bronze I',
    'Unranked'
);

CREATE TYPE rank_division AS ENUM(
    'IV',
    'III',
    'II',
    'I'
);

CREATE TYPE item_category AS ENUM(
    'Body', 
    'Decal', 
    'Paint Finish', 
    'Wheels', 
    'Rocket Boost', 
    'Toppers', 
    'Antenna', 
    'Goal Explosion', 
    'Trails', 
    'Player Banner', 
    'Engine Audio'
);

CREATE TYPE item_color AS ENUM(
    'Black', 
    'Burnt Sienna', 
    'Cobalt', 
    'Crimson', 
    'Forest Green', 
    'Grey', 
    'Lime', 
    'Orange', 
    'Pink', 
    'Purple', 
    'Saffron', 
    'Sky Blue', 
    'Titanium White'
);

CREATE TYPE item_certification AS ENUM(
    'Acrobat', 
    'Aviator', 
    'Goalkeeper', 
    'Guardian', 
    'Juggler', 
    'Paragon', 
    'Playmaker', 
    'Scorer', 
    'Show-Off', 
    'Sniper', 
    'Striker', 
    'Sweeper', 
    'Tactician', 
    'Turtle', 
    'Victor'
);

CREATE TYPE item_rarity AS ENUM(
    'Common', 
    'Uncommon', 
    'Rare', 
    'Very Rare', 
    'Import', 
    'Exotic', 
    'Black Market', 
    'Premium', 
    'Limited'
);

CREATE TYPE item_special_edition AS ENUM(
    'Inverted', 
    'Infinite', 
    'Holographic'
);

CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fname TEXT NOT NULL,
    lname TEXT NOT NULL,
    platform gaming_platform NOT NULL,
    gamertag TEXT NOT NULL,
    rocket_id TEXT NULL,
    rank user_rank NOT NULL,
    division rank_division NOT NULL,
    lft BOOLEAN NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password TEXT NOT NULL,
    bio VARCHAR(255),
    date_created TIMESTAMP DEFAULT now() NOT NULL
);

CREATE TABLE items (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category item_category NOT NULL,
    item TEXT NOT NULL,
    painted item_color NOT NULL,
    rarity item_rarity NOT NULL,
    certified item_certification NOT NULL,
    special_edition item_special_edition NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);

CREATE TABLE teams (
    userid INTEGER REFERENCES users(id) NOT NULL PRIMARY KEY,
    gamertag TEXT NOT NULL,
    platform gaming_platform NOT NULL,
    rank user_rank NOT NULL,
    division rank_division NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);

CREATE TABLE trades (
    id INTEGER UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    userid INTEGER REFERENCES users(id) NOT NULL,
    itemid INTEGER REFERENCES items(id) NOT NULL,
    tradeid INTEGER GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY (userid, itemid)
);

CREATE TABLE inventory (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    userid INTEGER REFERENCES users(id) NOT NULL,
    itemid INTEGER REFERENCES items(id) NOT NULL
);